name: Build Debian Package
description: |
  This Github Actions builds the package

inputs:
  pkg-dir:
    description: The directory where the debian package source is
    required: true
  build-dir:
    description: The directory where the package is built
    required: true
  run-lintian:
    description: Run lintian or not during the build
    default: false

runs:
  using: "composite"
  
  steps:

    # Normalize the name of the architecture
    # Build Architecture: The architecture of the machine performing the build (arm64 when native or amd64 when cross compiling).
    # This depends on the runner executing the build
    - name: Set Builder Arch variable
      shell: bash
      run: |
        if [ "${{ runner.arch }}" = "X64" ]; then
          echo "BUILD_ARCH=amd64" >> $GITHUB_ENV
        elif [ "${{ runner.arch }}" = "ARM64" ]; then
          echo "BUILD_ARCH=arm64" >> $GITHUB_ENV
        else
          echo "Unsupported architecture: ${{ runner.arch }}"
          exit 1
        fi

    - name: Prepare Workspace Structure For The Build
      shell: bash
      run: |
        echo "Listing the content of the workspace :"; tree

        mkdir ${{inputs.build-dir}}

        if grep -q 'quilt' ./package-repo/debian/source/format; then
          echo "Source format is quilt"
        elif grep -q 'native' ./package-repo/debian/source/format; then
          echo "Source format is native"
        else
          echo "Source format is unknown or unsupported"
          exit 1
        fi

    - name : Build Package
      shell: bash
      run: |
        cd ${{inputs.pkg-dir}}

        if [[ "${{inputs.run-lintian}}" == "true" ]]; then
          lintian_flag="--run-lintian"
        else
          lintian_flag="--no-run-lintian"
        fi

        if curl -sfI "http://pkg.qualcomm.com/dists/${{env.UBUNTU_DISTRIBUTION}}/Release" > /dev/null; then
          EXTRA_REPO="--extra-repository='deb [arch=arm64 trusted=yes] http://pkg.qualcomm.com ${{env.UBUNTU_DISTRIBUTION}}/stable main'"
        else
          EXTRA_REPO=""
        fi

        set +e

        # ℹ️ --git-ignore-branch is necessary because the debian branch actually checked out can be any (ex, debian/1.0.0) because we can build any previous tag 
        # ℹ️ chroot mode unshare is important to bypass privilege issues with the mounting
        # Host Architecture: The architecture for which the binaries are being built (invariably arm64).

        gbp buildpackage \
          --git-ignore-branch \
          --git-builder="sbuild --host=arm64 \
                                --build=${{env.BUILD_ARCH}} \
                                --dist=${{env.UBUNTU_DISTRUBUTION}} \
                                $lintian_flag \
                                --build-dir ../${{inputs.build-dir}} \
                                --build-dep-resolver=apt \
                                $EXTRA_REPO"

        RET=$?

        if (( RET == 0 )); then
          echo "✅ Successfully built package"
        else
          BUILD_LOG=$(find ../${{inputs.build-dir}} -maxdepth 1 -name "*.build" ! -type l)

          if [[ -n "$BUILD_LOG" ]]; then
            tail -n 500 "$BUILD_LOG"
            echo "❌ Build failed, printed the last 500 lines of the build log file"
          else
            echo "❌ Build failed, but no .build log file was found to print"
          fi

          exit 1
        fi
