#!/bin/bash
# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause
#
# ==============================================================================
# Script: gen-flash-dirs.sh
# ------------------------------------------------------------------------------
# Generates per-target, per-storage flash directories from a boards JSON array.
# rootfs.img is shared at the output root; all other images are per storage dir.
#
# Per-storage image placement:
#   nvme/ufs/emmc: efi.bin (4096-byte sectors for ufs/nvme, 512 for emmc)
#                  VolatileVars.bin patched into that target's own copy of
#                  efi.bin when "seed_volatile_vars": true in targets.json
#                  (see bootloader/patch-volatile-vars.sh) — other targets
#                  sharing the same source efi.bin are unaffected
#                  dtb.bin (only if the target has no spinor storage)
#                  rootfs.img referenced as ../../rootfs.img in rawprogram XMLs
#   spinor:        dtb.bin only (firmware-only; no efi or rootfs)
#
# Boot bin assembly per storage dir:
#   1. Copy boot bins from archive (auto-detects partition_<storage>/ subdir or flat root)
#   2. Run ptool with -m to generate fresh rawprogram*.xml with OS image filenames
#      already wired (efi=efi.bin, rootfs=../../rootfs.img, dtb_a/b=dtb.bin, cdt=cdt.bin)
#      Overwrites any partition files that came from the archive
#   3. Remove dangerous BLANK_GPT/WIPE files generated by ptool
#
# Usage:
#   gen-flash-dirs.sh \
#     --boards-json    '<json-array>'        \
#     --ptool-dir      <path/to/qcom-ptool>  \
#     --boot-bins-dir  <path/to/boot_bins>   \
#     --system-images  <path/to/images-dir>  \
#     --output-dir     <path/to/output>      \
#     [--contents-xml-in <path/to/contents.xml.in>]
#
# ==============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ------------------------------------------------------------------------------
# Sector size per storage type (ufs/nvme: 4096, emmc: 512)
# ------------------------------------------------------------------------------
sector_size_for() {
    case "$1" in
        ufs)  echo 4096 ;;
        nvme) echo 4096 ;;
        emmc) echo 512  ;;
        *)    echo 512  ;;
    esac
}

# ------------------------------------------------------------------------------
# Argument parsing
# ------------------------------------------------------------------------------
BOARDS_JSON=""
PTOOL_DIR=""
BOOT_BINS_DIR=""
SYSTEM_IMAGES_DIR=""
OUTPUT_DIR=""
CONTENTS_XML_IN=""

print_usage() {
    cat <<EOF
Usage:
  $0 --boards-json '<json>' --ptool-dir <dir> --boot-bins-dir <dir> \
     --system-images <dir> --output-dir <dir> [--contents-xml-in <file>]
EOF
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --boards-json)      BOARDS_JSON="$2";      shift 2 ;;
        --ptool-dir)        PTOOL_DIR="$2";         shift 2 ;;
        --boot-bins-dir)    BOOT_BINS_DIR="$2";     shift 2 ;;
        --system-images)    SYSTEM_IMAGES_DIR="$2"; shift 2 ;;
        --output-dir)       OUTPUT_DIR="$2";        shift 2 ;;
        --contents-xml-in)  CONTENTS_XML_IN="$2";   shift 2 ;;
        -h|--help)          print_usage; exit 0 ;;
        *) echo "[ERROR] Unknown argument: $1"; print_usage; exit 1 ;;
    esac
done

for var in BOARDS_JSON PTOOL_DIR BOOT_BINS_DIR SYSTEM_IMAGES_DIR OUTPUT_DIR; do
    if [[ -z "${!var}" ]]; then
        echo "[ERROR] --$(echo "$var" | tr '[:upper:]_' '[:lower:]-') is required"
        print_usage; exit 1
    fi
done

# Resolve all path arguments to absolute paths so they remain valid after pushd/popd
PTOOL_DIR=$(realpath "$PTOOL_DIR")
BOOT_BINS_DIR=$(realpath "$BOOT_BINS_DIR")
SYSTEM_IMAGES_DIR=$(realpath "$SYSTEM_IMAGES_DIR")
mkdir -p "$OUTPUT_DIR"
OUTPUT_DIR=$(realpath "$OUTPUT_DIR")
[[ -n "$CONTENTS_XML_IN" ]] && CONTENTS_XML_IN=$(realpath "$CONTENTS_XML_IN")

# qcom-ptool moved its Python scripts (gen_partition.py, ptool.py,
# gen_contents.py) from the repo root into a qcom_ptool/ package directory,
# and ptool.py now imports its sibling utils module as "qcom_ptool.utils".
# Support both layouts: platforms/ stays at the repo root either way, but
# the scripts directory and PYTHONPATH differ.
if [[ -f "${PTOOL_DIR}/qcom_ptool/ptool.py" ]]; then
    PTOOL_SCRIPTS_DIR="${PTOOL_DIR}/qcom_ptool"
    PTOOL_PYTHONPATH="${PTOOL_DIR}"
elif [[ -f "${PTOOL_DIR}/ptool.py" ]]; then
    PTOOL_SCRIPTS_DIR="${PTOOL_DIR}"
    PTOOL_PYTHONPATH=""
else
    echo "[ERROR] ptool.py not found under ${PTOOL_DIR} or ${PTOOL_DIR}/qcom_ptool"
    exit 1
fi

command -v python3   &>/dev/null || { echo "[ERROR] python3 is required"; exit 1; }
command -v jq        &>/dev/null || { echo "[ERROR] jq is required";     exit 1; }
command -v xmlstarlet &>/dev/null || { echo "[ERROR] xmlstarlet is required"; exit 1; }

# ------------------------------------------------------------------------------
# Place rootfs.img at the output root (shared by all targets)
# ------------------------------------------------------------------------------
if [[ ! -f "${SYSTEM_IMAGES_DIR}/rootfs.img" ]]; then
    echo "[ERROR] rootfs.img not found in ${SYSTEM_IMAGES_DIR} — cannot build flash package"
    exit 1
fi
cp --preserve=mode,timestamps -v \
    "${SYSTEM_IMAGES_DIR}/rootfs.img" "${OUTPUT_DIR}/rootfs.img"

# ------------------------------------------------------------------------------
# Helper: remove dangerous ptool wipe files from a flash dir
# ------------------------------------------------------------------------------
cleanup_flash_dir() {
    local dir="$1"
    # NOTE: this is always called on a partition_<storage>/ subdirectory, never on
    # the PTOOL_WORK root. The root-level partition_<storage>.xml files used by
    # gen_contents.py are one level up and are never touched by this function.
    rm -vf "${dir}"/rawprogram*_BLANK_GPT.xml
    rm -vf "${dir}"/rawprogram*_WIPE_PARTITIONS.xml
    rm -vf "${dir}"/wipe_rawprogram*.xml
    # Remove any intermediate partition XML files inside the subdir (not needed in output)
    rm -vf "${dir}"/partition_*.xml
}

# ------------------------------------------------------------------------------
# Cache: ptool platform -> work dir (avoid regenerating for shared platforms)
# ------------------------------------------------------------------------------
declare -A GENERATED_PLATFORMS

# ------------------------------------------------------------------------------
# Main loop: iterate over boards/targets
# ------------------------------------------------------------------------------
BOARD_COUNT=$(echo "$BOARDS_JSON" | jq 'length')
echo "[INFO] Processing ${BOARD_COUNT} target(s)"

for i in $(seq 0 $((BOARD_COUNT - 1))); do
    BOARD_NAME=$(echo "$BOARDS_JSON"     | jq -r ".[$i].name")
    PTOOL_PLATFORM=$(echo "$BOARDS_JSON" | jq -r ".[$i].ptool_platform")
    CDT_FILENAME=$(echo "$BOARDS_JSON"   | jq -r ".[$i].cdt_filename // empty")
    SEED_VOLATILE_VARS=$(echo "$BOARDS_JSON" | jq -r ".[$i].seed_volatile_vars // false")
    SEED_VOLATILE_VARS_CONFIG=$(echo "$BOARDS_JSON" | jq -r ".[$i].seed_volatile_vars_config // empty")
    if [[ -n "$SEED_VOLATILE_VARS_CONFIG" ]]; then
        # Paths in targets.json are relative to the qcom-distro-images repo
        # root, i.e. two levels above boot_bins/ (see contents_xml_in below).
        SEED_VOLATILE_VARS_CONFIG="$(dirname "$(dirname "$BOOT_BINS_DIR")")/${SEED_VOLATILE_VARS_CONFIG}"
        if [[ ! -f "$SEED_VOLATILE_VARS_CONFIG" ]]; then
            echo "[ERROR] seed_volatile_vars_config not found: ${SEED_VOLATILE_VARS_CONFIG}"
            exit 1
        fi
    fi

    echo ""
    echo "========================================================"
    echo "[INFO] Target ${i}: ${BOARD_NAME}  (ptool: ${PTOOL_PLATFORM})"
    echo "========================================================"

    PLATFORM_DIR="${PTOOL_DIR}/platforms/${PTOOL_PLATFORM}"
    if [[ ! -d "$PLATFORM_DIR" ]]; then
        echo "[ERROR] qcom-ptool platform directory not found: ${PLATFORM_DIR}"
        exit 1
    fi

    # ------------------------------------------------------------------
    # Determine which storage types this target supports
    # Always use qcom-ptool/platforms/ as the source of truth.
    # ------------------------------------------------------------------
    HAS_SPINOR=false
    SUPPORTED_STORAGES=()
    for storage in nvme ufs emmc spinor; do
        if [[ -f "${PLATFORM_DIR}/${storage}/partitions.conf" ]]; then
            SUPPORTED_STORAGES+=("$storage")
            [[ "$storage" == "spinor" ]] && HAS_SPINOR=true
        fi
    done
    if [[ ${#SUPPORTED_STORAGES[@]} -eq 0 ]]; then
        echo "[ERROR] No supported storage types found for platform: ${PTOOL_PLATFORM}"
        echo "[ERROR] Expected partitions.conf in ${PLATFORM_DIR}/<storage>/"
        exit 1
    fi
    echo "[INFO] Supported storages: ${SUPPORTED_STORAGES[*]}"
    echo "[INFO] Has spinor: ${HAS_SPINOR}"

    # ------------------------------------------------------------------
    # Locate CDT file for this board.
    # Resolved before ptool so the filename can be passed via -m.
    # Each CDT zip contains exactly one .bin — no fallback or count needed.
    # ------------------------------------------------------------------
    CDT_SRC=""
    if [[ -n "$CDT_FILENAME" ]]; then
        CDT_SRC=$(find "${BOOT_BINS_DIR}/cdt_${BOARD_NAME}" \
            -name "$CDT_FILENAME" 2>/dev/null | head -1 || true)
        if [[ -z "$CDT_SRC" ]]; then
            echo "[ERROR] CDT file '${CDT_FILENAME}' not found for board ${BOARD_NAME}"
            exit 1
        else
            echo "[INFO] CDT file: ${CDT_SRC}"
        fi
    fi

    # ------------------------------------------------------------------
    # Generate ptool partition tables — always, for all storage types.
    # Pass -m to wire OS image filenames at generation time (same approach
    # as qcom-deb-images) so rawprogram XMLs come out with correct filenames
    # without needing post-generation patching.
    # GENERATED_PLATFORMS cache deduplicates across boards sharing the
    # same ptool platform.
    # ------------------------------------------------------------------
    PTOOL_WORK="${BOOT_BINS_DIR}/ptool_${PTOOL_PLATFORM}"

    if [[ -z "${GENERATED_PLATFORMS[$PTOOL_PLATFORM]+x}" ]]; then
        echo "[INFO] Generating partition tables for platform: ${PTOOL_PLATFORM}"
        mkdir -p "$PTOOL_WORK"
        pushd "$PTOOL_WORK" > /dev/null

        for storage in "${SUPPORTED_STORAGES[@]}"; do
            CONF="${PLATFORM_DIR}/${storage}/partitions.conf"
            echo "[INFO]   Generating ${storage} partition table"

            # Build partition filename map for this storage type.
            # Labels not present in partitions.conf are silently ignored by gen_partition.py.
            case "$storage" in
                nvme|ufs|emmc)
                    PART_MAP="efi=efi.bin,rootfs=../../rootfs.img"
                    PART_MAP="${PART_MAP},dtb_a=dtb.bin,dtb_b=dtb.bin"
                    ;;
                spinor)
                    PART_MAP="dtb_a=dtb.bin,dtb_b=dtb.bin"
                    ;;
                *)
                    PART_MAP=""
                    ;;
            esac
            # Add CDT mapping if a CDT file is configured for this board
            if [[ -n "$CDT_SRC" ]]; then
                PART_MAP="${PART_MAP},cdt=cdt.bin"
            fi

            python3 "${PTOOL_SCRIPTS_DIR}/gen_partition.py" \
                -i "$CONF" -o "partition_${storage}.xml" \
                ${PART_MAP:+-m "$PART_MAP"}
            PYTHONPATH="${PTOOL_PYTHONPATH}" python3 "${PTOOL_SCRIPTS_DIR}/ptool.py" \
                -x "partition_${storage}.xml" \
                -t "./partition_${storage}"
            cleanup_flash_dir "./partition_${storage}"
        done

        popd > /dev/null
        GENERATED_PLATFORMS[$PTOOL_PLATFORM]=1
    else
        echo "[INFO] Reusing cached partition tables for platform: ${PTOOL_PLATFORM}"
    fi

    # ------------------------------------------------------------------
    # Build one directory per storage type: <output>/<target>/<storage>/
    # ------------------------------------------------------------------
    TARGET_DIR="${OUTPUT_DIR}/${BOARD_NAME}"
    BOARD_BOOT_DIR="${BOOT_BINS_DIR}/bins_${BOARD_NAME}"

    for storage in "${SUPPORTED_STORAGES[@]}"; do
        STORAGE_DIR="${TARGET_DIR}/${storage}"
        PARTITION_DIR="${PTOOL_WORK}/partition_${storage}"

        echo ""
        echo "[INFO] Building ${BOARD_NAME}/${storage}/"
        mkdir -p "$STORAGE_DIR"

        # 1. Copy boot binaries from archive first.
        #    Auto-detect layout: if partition_<storage>/ subdir exists in the
        #    archive, boot bins are there; otherwise they are flat at archive root.
        #    Copy everything (including any pre-existing partition files from the
        #    archive) — ptool will overwrite them in step 2.
        if [[ -d "${BOARD_BOOT_DIR}/partition_${storage}" ]]; then
            BOOT_BIN_SRC="${BOARD_BOOT_DIR}/partition_${storage}"
        else
            BOOT_BIN_SRC="${BOARD_BOOT_DIR}/${storage}"
        fi
        if [[ ! -d "$BOOT_BIN_SRC" ]]; then
            BOOT_BIN_SRC="${BOARD_BOOT_DIR}"
        fi
        if [[ -d "$BOOT_BIN_SRC" ]]; then
            cp --preserve=mode,timestamps -av "${BOOT_BIN_SRC}/." "${STORAGE_DIR}/"
            echo "[INFO] Copied boot bins from: ${BOOT_BIN_SRC}"
        else
            echo "[ERROR] Boot bins directory not found: ${BOOT_BIN_SRC}"
            exit 1
        fi

        # 2. Copy ptool-generated partition files — overwrites any partition
        #    files that came from the archive in step 1.
        cp --preserve=mode,timestamps -av "${PARTITION_DIR}/." "${STORAGE_DIR}/"

        # 3. Remove dangerous wipe files generated by ptool.
        cleanup_flash_dir "$STORAGE_DIR"

        # 4. CDT
        if [[ -n "$CDT_SRC" ]]; then
            cp --preserve=mode,timestamps -v "$CDT_SRC" "${STORAGE_DIR}/cdt.bin"
        fi

        # 5. Copy system images into this storage dir.
        #    spinor: dtb.bin only (firmware-only storage, no OS images).
        #    nvme/ufs/emmc: efi.bin (sector-size matched) + dtb.bin if no spinor.
        #    rootfs.img is at the output root, referenced as ../../rootfs.img in rawprogram.
        case "$storage" in
            spinor)
                if [[ -f "${SYSTEM_IMAGES_DIR}/dtb.bin" ]]; then
                    cp --preserve=mode,timestamps -v \
                        "${SYSTEM_IMAGES_DIR}/dtb.bin" "${STORAGE_DIR}/dtb.bin"
                else
                    echo "[ERROR] dtb.bin not found for spinor"
                    exit 1
                fi
                ;;
            nvme|ufs|emmc)
                SECTOR_SIZE=$(sector_size_for "$storage")
                EFI_SRC="${SYSTEM_IMAGES_DIR}/efi_${SECTOR_SIZE}.bin"
                [[ ! -f "$EFI_SRC" ]] && EFI_SRC="${SYSTEM_IMAGES_DIR}/efi.bin"
                if [[ -f "$EFI_SRC" ]]; then
                    cp --preserve=mode,timestamps -v "$EFI_SRC" "${STORAGE_DIR}/efi.bin"
                else
                    echo "[ERROR] efi.bin not found for ${storage} (sector size ${SECTOR_SIZE})"
                    exit 1
                fi

                if [[ "$SEED_VOLATILE_VARS" == "true" ]]; then
                    PATCH_VOLATILE_VARS_ARGS=(--efi "${STORAGE_DIR}/efi.bin")
                    if [[ -n "$SEED_VOLATILE_VARS_CONFIG" ]]; then
                        PATCH_VOLATILE_VARS_ARGS+=(--config "$SEED_VOLATILE_VARS_CONFIG")
                    fi
                    "${SCRIPT_DIR}/../bootloader/patch-volatile-vars.sh" \
                        "${PATCH_VOLATILE_VARS_ARGS[@]}"
                fi

                if [[ "$HAS_SPINOR" == "false" ]]; then
                    if [[ -f "${SYSTEM_IMAGES_DIR}/dtb.bin" ]]; then
                        cp --preserve=mode,timestamps -v \
                            "${SYSTEM_IMAGES_DIR}/dtb.bin" "${STORAGE_DIR}/dtb.bin"
                    else
                        echo "[ERROR] dtb.bin not found for ${storage} (no spinor)"
                        exit 1
                    fi
                fi
                ;;
        esac
    done
done


# ------------------------------------------------------------------------------
# Generate contents.xml per target:
#   - Target WITH spinor:    contents.xml in <target>/spinor/
#                            OS paths patched to ../nvme/, ../ufs/ etc.
#   - Target WITHOUT spinor: contents.xml per storage dir
#                            all paths at . (same directory)
# ------------------------------------------------------------------------------
echo ""
echo "[INFO] Generating contents.xml per target"

for k in $(seq 0 $((BOARD_COUNT - 1))); do
    CX_BOARD=$(echo "$BOARDS_JSON" | jq -r ".[$k].name")
    CX_PTOOL=$(echo "$BOARDS_JSON" | jq -r ".[$k].ptool_platform")
    CX_CXI=$(echo "$BOARDS_JSON"   | jq -r "if .[$k].contents_xml_in then .[$k].contents_xml_in else empty end // \"\"")
    CX_PLATFORM_DIR="${PTOOL_DIR}/platforms/${CX_PTOOL}"
    CX_PTOOL_WORK="${BOOT_BINS_DIR}/ptool_${CX_PTOOL}"
    CX_TARGET_DIR="${OUTPUT_DIR}/${CX_BOARD}"

    echo ""
    echo "[INFO] contents.xml for target: ${CX_BOARD}"

    # Storage discovery always from qcom-ptool/platforms/
    CX_HAS_SPINOR=false
    CX_STORAGES=()
    for s in nvme ufs emmc spinor; do
        if [[ -f "${CX_PLATFORM_DIR}/${s}/partitions.conf" ]]; then
            CX_STORAGES+=("$s")
            [[ "$s" == "spinor" ]] && CX_HAS_SPINOR=true
        fi
    done

    if [[ "$CX_HAS_SPINOR" == "true" ]]; then
        # Spinor target: one contents.xml inside <target>/spinor/
        CX_TEMPLATE=""
        # Template resolution order:
        #   1. --contents-xml-in arg (passed from workflow when contents_xml_in is set)
        #   2. contents_xml_in path relative to repo root (two levels up from boot_bins/)
        #   3. qcom-ptool platforms/<ptool>/spinor/contents.xml.in
        if [[ -n "$CX_CXI" && -f "$CONTENTS_XML_IN" ]]; then
            CX_TEMPLATE="$CONTENTS_XML_IN"
        elif [[ -n "$CX_CXI" ]]; then
            CX_TEMPLATE_REL="$(dirname "$(dirname "$BOOT_BINS_DIR")")/${CX_CXI}"
            [[ -f "$CX_TEMPLATE_REL" ]] && CX_TEMPLATE="$CX_TEMPLATE_REL"
        fi
        if [[ -z "$CX_TEMPLATE" && -f "${CX_PLATFORM_DIR}/spinor/contents.xml.in" ]]; then
            CX_TEMPLATE="${CX_PLATFORM_DIR}/spinor/contents.xml.in"
        fi

        CX_PARTITION_XML="${CX_PTOOL_WORK}/partition_spinor.xml"
        if [[ -n "$CX_TEMPLATE" && -f "$CX_PARTITION_XML" ]]; then
            CX_OUT="${CX_TARGET_DIR}/spinor/contents.xml"
            python3 "${PTOOL_SCRIPTS_DIR}/gen_contents.py" \
                -t "$CX_TEMPLATE" \
                -p "$CX_PARTITION_XML" \
                -o "$CX_OUT"
            echo "[INFO] Written: ${CX_OUT}"

            # Patch rootfs.img path to ../../rootfs.img
            xmlstarlet ed -L \
                -u "//download_file[file_name='rootfs.img']/file_path" \
                -v "../../" \
                "$CX_OUT"
            echo "[INFO] Patched rootfs.img path in ${CX_OUT}"

            # Patch OS storage paths: NVME/ -> ../nvme/, UFS/ -> ../ufs/ etc.
            # Use xmlstarlet for exact text matching — robust against casing changes in templates.
            xmlstarlet ed -L \
                -u "//file_path[text()='NVME/']" -v "../nvme/" \
                -u "//file_path[text()='UFS/']"  -v "../ufs/"  \
                -u "//file_path[text()='EMMC/']" -v "../emmc/" \
                "$CX_OUT"
            echo "[INFO] Patched OS storage paths in ${CX_OUT}"
        else
            echo "[WARN] Skipping spinor contents.xml for ${CX_BOARD}: template or partition XML not found"
        fi

    else
        # No-spinor target: one contents.xml per storage dir
        for s in "${CX_STORAGES[@]}"; do
            CX_TEMPLATE=""
            [[ -f "${CX_PLATFORM_DIR}/${s}/contents.xml.in" ]] && \
                CX_TEMPLATE="${CX_PLATFORM_DIR}/${s}/contents.xml.in"
            CX_PARTITION_XML="${CX_PTOOL_WORK}/partition_${s}.xml"
            if [[ -n "$CX_TEMPLATE" && -f "$CX_PARTITION_XML" ]]; then
                CX_OUT="${CX_TARGET_DIR}/${s}/contents.xml"
                python3 "${PTOOL_SCRIPTS_DIR}/gen_contents.py" \
                    -t "$CX_TEMPLATE" \
                    -p "$CX_PARTITION_XML" \
                    -o "$CX_OUT"
                echo "[INFO] Written: ${CX_OUT}"
                # Patch rootfs.img path to ../../rootfs.img
                xmlstarlet ed -L \
                    -u "//download_file[file_name='rootfs.img']/file_path" \
                    -v "../../" \
                    "$CX_OUT"
                echo "[INFO] Patched rootfs.img path in ${CX_OUT}"
            else
                echo "[INFO] No contents.xml.in for ${CX_BOARD}/${s} — skipping"
            fi
        done
    fi
done

echo ""
echo "[INFO] gen-flash-dirs.sh complete. Output: ${OUTPUT_DIR}"
