#!/bin/bash
# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause
#
# ==============================================================================
# Script: gen-flash-dirs.sh
# ------------------------------------------------------------------------------
# Description:
#   Generates per-target, per-storage flash directories from a boards JSON
#   array. All targets share the same rootfs.img (placed at the output root).
#
#   Storage layout rules (Table 1):
#     nvme, ufs, emmc:
#       - always: efi.bin (sector-size matched)
#       - rootfs.img: referenced via ../../rootfs.img in rawprogram XMLs
#       - dtb.bin: only if the target has NO spinor storage
#     spinor:
#       - always: dtb.bin
#       - never:  efi.bin, rootfs.img  (firmware-only storage)
#
#   Sector sizes (Table 2):
#     ufs  -> 4096 bytes
#     nvme -> 4096 bytes
#     emmc -> 512  bytes
#
#   Boot bin copy order (per storage dir):
#     1. Copy all boot bin files from archive (including any pre-existing
#        rawprogram/patch/gpt/zeros — they will be overwritten in step 2)
#     2. Run ptool — generates fresh rawprogram*.xml, patch*.xml, gpt_*.bin,
#        zeros_*.bin, overwriting anything from the archive
#     3. cleanup_flash_dir — removes BLANK_GPT/WIPE files generated by ptool
#
#   Storage types are always discovered from qcom-ptool/platforms/<ptool_platform>/
#   regardless of archive layout.
#
#   pre_partitioned flag: controls only where boot binaries are found:
#     true  -> bins_<board>/partition_<storage>/  (archive has per-storage subdirs)
#     false -> bins_<board>/                      (archive has flat layout)
#   Auto-detected: if partition_<storage>/ subdir exists, use it; else use flat.
#
# Output layout:
#   <output-dir>/
#     rootfs.img                        (shared, at root)
#     <target-name>/
#       <storage>/
#         rawprogram*.xml, patch*.xml   (from ptool — always fresh)
#         gpt_*.bin, zeros_*.bin        (from ptool — always fresh)
#         <boot-bins>                   (from archive)
#         cdt.bin                       (if cdt configured)
#         efi.bin                       (nvme/ufs/emmc only, sector-size matched)
#         dtb.bin                       (spinor always; nvme/ufs/emmc if no spinor)
#       <storage>/contents.xml          (no-spinor targets: per storage dir)
#       spinor/contents.xml             (spinor targets: in spinor dir, OS paths patched)
#
# Usage:
#   gen-flash-dirs.sh \
#     --boards-json    '<json-array>'        \
#     --ptool-dir      <path/to/qcom-ptool>  \
#     --boot-bins-dir  <path/to/boot_bins>   \
#     --system-images  <path/to/images-dir>  \
#     --output-dir     <path/to/output>      \
#     [--contents-xml-in <path/to/contents.xml.in>]
#
# ==============================================================================

set -euo pipefail

# ------------------------------------------------------------------------------
# Sector size map (Table 2)
# ------------------------------------------------------------------------------
sector_size_for() {
    case "$1" in
        ufs)  echo 4096 ;;
        nvme) echo 4096 ;;
        emmc) echo 512  ;;
        *)    echo 512  ;;
    esac
}

# ------------------------------------------------------------------------------
# Argument parsing
# ------------------------------------------------------------------------------
BOARDS_JSON=""
PTOOL_DIR=""
BOOT_BINS_DIR=""
SYSTEM_IMAGES_DIR=""
OUTPUT_DIR=""
CONTENTS_XML_IN=""

print_usage() {
    cat <<EOF
Usage:
  $0 --boards-json '<json>' --ptool-dir <dir> --boot-bins-dir <dir> \
     --system-images <dir> --output-dir <dir> [--contents-xml-in <file>]
EOF
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --boards-json)      BOARDS_JSON="$2";      shift 2 ;;
        --ptool-dir)        PTOOL_DIR="$2";         shift 2 ;;
        --boot-bins-dir)    BOOT_BINS_DIR="$2";     shift 2 ;;
        --system-images)    SYSTEM_IMAGES_DIR="$2"; shift 2 ;;
        --output-dir)       OUTPUT_DIR="$2";        shift 2 ;;
        --contents-xml-in)  CONTENTS_XML_IN="$2";   shift 2 ;;
        -h|--help)          print_usage; exit 0 ;;
        *) echo "[ERROR] Unknown argument: $1"; print_usage; exit 1 ;;
    esac
done

for var in BOARDS_JSON PTOOL_DIR BOOT_BINS_DIR SYSTEM_IMAGES_DIR OUTPUT_DIR; do
    if [[ -z "${!var}" ]]; then
        echo "[ERROR] --$(echo "$var" | tr '[:upper:]_' '[:lower:]-') is required"
        print_usage; exit 1
    fi
done

# Resolve all path arguments to absolute paths so they remain valid after pushd/popd
PTOOL_DIR=$(realpath "$PTOOL_DIR")
BOOT_BINS_DIR=$(realpath "$BOOT_BINS_DIR")
SYSTEM_IMAGES_DIR=$(realpath "$SYSTEM_IMAGES_DIR")
OUTPUT_DIR=$(realpath -m "$OUTPUT_DIR")
[[ -n "$CONTENTS_XML_IN" ]] && CONTENTS_XML_IN=$(realpath "$CONTENTS_XML_IN")

command -v python3 &>/dev/null || { echo "[ERROR] python3 is required"; exit 1; }
command -v jq     &>/dev/null || { echo "[ERROR] jq is required";     exit 1; }

mkdir -p "$OUTPUT_DIR"

# ------------------------------------------------------------------------------
# Place rootfs.img at the output root (shared by all targets)
# ------------------------------------------------------------------------------
if [[ -f "${SYSTEM_IMAGES_DIR}/rootfs.img" ]]; then
    cp --preserve=mode,timestamps -v \
        "${SYSTEM_IMAGES_DIR}/rootfs.img" "${OUTPUT_DIR}/rootfs.img"
else
    echo "[WARN] rootfs.img not found in ${SYSTEM_IMAGES_DIR}"
fi

# ------------------------------------------------------------------------------
# Helper: remove dangerous ptool wipe files from a flash dir
# ------------------------------------------------------------------------------
cleanup_flash_dir() {
    local dir="$1"
    rm -vf "${dir}"/rawprogram*_BLANK_GPT.xml
    rm -vf "${dir}"/rawprogram*_WIPE_PARTITIONS.xml
    rm -vf "${dir}"/wipe_rawprogram*.xml
}

# ------------------------------------------------------------------------------
# Cache: ptool platform -> work dir (avoid regenerating for shared platforms)
# ------------------------------------------------------------------------------
declare -A GENERATED_PLATFORMS

# ------------------------------------------------------------------------------
# Main loop: iterate over boards/targets
# ------------------------------------------------------------------------------
BOARD_COUNT=$(echo "$BOARDS_JSON" | jq 'length')
echo "[INFO] Processing ${BOARD_COUNT} target(s)"

for i in $(seq 0 $((BOARD_COUNT - 1))); do
    BOARD_NAME=$(echo "$BOARDS_JSON"     | jq -r ".[$i].name")
    PTOOL_PLATFORM=$(echo "$BOARDS_JSON" | jq -r ".[$i].ptool_platform")
    CDT_FILENAME=$(echo "$BOARDS_JSON"   | jq -r ".[$i].cdt_filename // empty")

    echo ""
    echo "========================================================"
    echo "[INFO] Target ${i}: ${BOARD_NAME}  (ptool: ${PTOOL_PLATFORM})"
    echo "========================================================"

    PLATFORM_DIR="${PTOOL_DIR}/platforms/${PTOOL_PLATFORM}"
    if [[ ! -d "$PLATFORM_DIR" ]]; then
        echo "[ERROR] qcom-ptool platform directory not found: ${PLATFORM_DIR}"
        exit 1
    fi

    # ------------------------------------------------------------------
    # Determine which storage types this target supports
    # Always use qcom-ptool/platforms/ as the source of truth.
    # ------------------------------------------------------------------
    HAS_SPINOR=false
    SUPPORTED_STORAGES=()
    for storage in nvme ufs emmc spinor; do
        if [[ -f "${PLATFORM_DIR}/${storage}/partitions.conf" ]]; then
            SUPPORTED_STORAGES+=("$storage")
            [[ "$storage" == "spinor" ]] && HAS_SPINOR=true
        fi
    done
    echo "[INFO] Supported storages: ${SUPPORTED_STORAGES[*]}"
    echo "[INFO] Has spinor: ${HAS_SPINOR}"

    # ------------------------------------------------------------------
    # Generate ptool partition tables — always, for all storage types.
    # GENERATED_PLATFORMS cache deduplicates across boards sharing the
    # same ptool platform.
    # ------------------------------------------------------------------
    PTOOL_WORK="${BOOT_BINS_DIR}/ptool_${PTOOL_PLATFORM}"

    if [[ -z "${GENERATED_PLATFORMS[$PTOOL_PLATFORM]+x}" ]]; then
        echo "[INFO] Generating partition tables for platform: ${PTOOL_PLATFORM}"
        mkdir -p "$PTOOL_WORK"
        pushd "$PTOOL_WORK" > /dev/null

        for storage in "${SUPPORTED_STORAGES[@]}"; do
            CONF="${PLATFORM_DIR}/${storage}/partitions.conf"
            echo "[INFO]   Generating ${storage} partition table"
            python3 "${PTOOL_DIR}/gen_partition.py" \
                -i "$CONF" -o "partition_${storage}.xml"
            python3 "${PTOOL_DIR}/ptool.py" \
                -x "partition_${storage}.xml" \
                -t "./partition_${storage}"
            cleanup_flash_dir "./partition_${storage}"
        done

        popd > /dev/null
        GENERATED_PLATFORMS[$PTOOL_PLATFORM]=1
    else
        echo "[INFO] Reusing cached partition tables for platform: ${PTOOL_PLATFORM}"
    fi

    # ------------------------------------------------------------------
    # Locate CDT file for this board
    # ------------------------------------------------------------------
    CDT_SRC=""
    if [[ -n "$CDT_FILENAME" ]]; then
        CDT_SRC=$(find "${BOOT_BINS_DIR}/cdt_${BOARD_NAME}" \
            -name "$CDT_FILENAME" 2>/dev/null | head -1 || true)
        if [[ -z "$CDT_SRC" ]]; then
            CDT_SRC=$(find "${BOOT_BINS_DIR}/cdt_${BOARD_NAME}" \
                -name '*.bin' 2>/dev/null | head -1 || true)
        fi
        if [[ -z "$CDT_SRC" ]]; then
            echo "[WARN] CDT file '${CDT_FILENAME}' not found for board ${BOARD_NAME}"
        else
            echo "[INFO] CDT file: ${CDT_SRC}"
        fi
    fi

    # ------------------------------------------------------------------
    # Build one directory per storage type: <output>/<target>/<storage>/
    # ------------------------------------------------------------------
    TARGET_DIR="${OUTPUT_DIR}/${BOARD_NAME}"
    BOARD_BOOT_DIR="${BOOT_BINS_DIR}/bins_${BOARD_NAME}"

    for storage in "${SUPPORTED_STORAGES[@]}"; do
        STORAGE_DIR="${TARGET_DIR}/${storage}"
        PARTITION_DIR="${PTOOL_WORK}/partition_${storage}"

        echo ""
        echo "[INFO] Building ${BOARD_NAME}/${storage}/"
        mkdir -p "$STORAGE_DIR"

        # 1. Copy boot binaries from archive first.
        #    Auto-detect layout: if partition_<storage>/ subdir exists in the
        #    archive, boot bins are there; otherwise they are flat at archive root.
        #    Copy everything (including any pre-existing partition files from the
        #    archive) — ptool will overwrite them in step 2.
        BOOT_BIN_SRC="${BOARD_BOOT_DIR}/partition_${storage}"
        if [[ ! -d "$BOOT_BIN_SRC" ]]; then
            BOOT_BIN_SRC="${BOARD_BOOT_DIR}"
        fi
        if [[ -d "$BOOT_BIN_SRC" ]]; then
            cp --preserve=mode,timestamps -av "${BOOT_BIN_SRC}/." "${STORAGE_DIR}/"
            echo "[INFO] Copied boot bins from: ${BOOT_BIN_SRC}"
        else
            echo "[WARN] Boot bins directory not found: ${BOOT_BIN_SRC}"
        fi

        # 2. Copy ptool-generated partition files — overwrites any partition
        #    files that came from the archive in step 1.
        cp --preserve=mode,timestamps -av "${PARTITION_DIR}/." "${STORAGE_DIR}/"

        # 3. Remove dangerous wipe files generated by ptool.
        cleanup_flash_dir "$STORAGE_DIR"

        # 4. CDT
        if [[ -n "$CDT_SRC" ]]; then
            cp --preserve=mode,timestamps -v "$CDT_SRC" "${STORAGE_DIR}/cdt.bin"
        fi

        # 5. Post-process rawprogram XMLs to wire OS image filenames.
        #    Rules (Table 1):
        #      nvme/ufs/emmc: efi label -> efi.bin, rootfs label -> ../../rootfs.img
        #      spinor:        dtb_a/dtb_b labels -> dtb.bin
        case "$storage" in
            nvme|ufs|emmc)
                for xml in "${STORAGE_DIR}"/rawprogram*.xml; do
                    [[ -f "$xml" ]] || continue
                    sed -i -E 's/filename=""([^>]*label="efi")/filename="efi.bin"\1/g' "$xml"
                    sed -i -E 's|filename=""([^>]*label="rootfs")|filename="../../rootfs.img"\1|g' "$xml"
                    sed -i 's|filename="rootfs\.img"|filename="../../rootfs.img"|g' "$xml"
                    echo "[INFO] Patched efi/rootfs filenames in $(basename "$xml")"
                done
                ;;
            spinor)
                for xml in "${STORAGE_DIR}"/rawprogram*.xml; do
                    [[ -f "$xml" ]] || continue
                    sed -i -E 's/filename=""([^>]*label="dtb_a")/filename="dtb.bin"\1/g' "$xml"
                    sed -i -E 's/filename=""([^>]*label="dtb_b")/filename="dtb.bin"\1/g' "$xml"
                    echo "[INFO] Patched dtb_a/dtb_b filenames in $(basename "$xml")"
                done
                ;;
        esac

        # 6. System images — apply Table 1 rules
        case "$storage" in
            spinor)
                if [[ -f "${SYSTEM_IMAGES_DIR}/dtb.bin" ]]; then
                    cp --preserve=mode,timestamps -v \
                        "${SYSTEM_IMAGES_DIR}/dtb.bin" "${STORAGE_DIR}/dtb.bin"
                else
                    echo "[WARN] dtb.bin not found for spinor"
                fi
                ;;
            nvme|ufs|emmc)
                SECTOR_SIZE=$(sector_size_for "$storage")
                EFI_SRC="${SYSTEM_IMAGES_DIR}/efi_${SECTOR_SIZE}.bin"
                [[ ! -f "$EFI_SRC" ]] && EFI_SRC="${SYSTEM_IMAGES_DIR}/efi.bin"
                if [[ -f "$EFI_SRC" ]]; then
                    cp --preserve=mode,timestamps -v "$EFI_SRC" "${STORAGE_DIR}/efi.bin"
                else
                    echo "[WARN] efi.bin not found for ${storage} (sector size ${SECTOR_SIZE})"
                fi

                if [[ "$HAS_SPINOR" == "false" ]]; then
                    if [[ -f "${SYSTEM_IMAGES_DIR}/dtb.bin" ]]; then
                        cp --preserve=mode,timestamps -v \
                            "${SYSTEM_IMAGES_DIR}/dtb.bin" "${STORAGE_DIR}/dtb.bin"
                    else
                        echo "[WARN] dtb.bin not found for ${storage} (no spinor fallback)"
                    fi
                fi
                ;;
        esac
    done
done

# ------------------------------------------------------------------------------
# Generate contents.xml per target:
#   - Target WITH spinor:    contents.xml in <target>/spinor/
#                            OS paths patched to ../nvme/, ../ufs/ etc.
#   - Target WITHOUT spinor: contents.xml per storage dir
#                            all paths at . (same directory)
# ------------------------------------------------------------------------------
echo ""
echo "[INFO] Generating contents.xml per target"

BOARD_COUNT_CX=$(echo "$BOARDS_JSON" | jq 'length')
for k in $(seq 0 $((BOARD_COUNT_CX - 1))); do
    CX_BOARD=$(echo "$BOARDS_JSON" | jq -r ".[$k].name")
    CX_PTOOL=$(echo "$BOARDS_JSON" | jq -r ".[$k].ptool_platform")
    CX_CXI=$(echo "$BOARDS_JSON"   | jq -r "if .[$k].contents_xml_in then .[$k].contents_xml_in else empty end // \"\"")
    CX_PLATFORM_DIR="${PTOOL_DIR}/platforms/${CX_PTOOL}"
    CX_PTOOL_WORK="${BOOT_BINS_DIR}/ptool_${CX_PTOOL}"
    CX_TARGET_DIR="${OUTPUT_DIR}/${CX_BOARD}"

    echo ""
    echo "[INFO] contents.xml for target: ${CX_BOARD}"

    # Storage discovery always from qcom-ptool/platforms/
    CX_HAS_SPINOR=false
    CX_STORAGES=()
    for s in nvme ufs emmc spinor; do
        if [[ -f "${CX_PLATFORM_DIR}/${s}/partitions.conf" ]]; then
            CX_STORAGES+=("$s")
            [[ "$s" == "spinor" ]] && CX_HAS_SPINOR=true
        fi
    done

    if [[ "$CX_HAS_SPINOR" == "true" ]]; then
        # Spinor target: one contents.xml inside <target>/spinor/
        CX_TEMPLATE=""
        if [[ -n "$CX_CXI" && -f "$CONTENTS_XML_IN" ]]; then
            CX_TEMPLATE="$CONTENTS_XML_IN"
        elif [[ -n "$CX_CXI" ]]; then
            CX_TEMPLATE_REL="$(dirname "$(dirname "$BOOT_BINS_DIR")")/${CX_CXI}"
            [[ -f "$CX_TEMPLATE_REL" ]] && CX_TEMPLATE="$CX_TEMPLATE_REL"
        fi
        if [[ -z "$CX_TEMPLATE" && -f "${CX_PLATFORM_DIR}/spinor/contents.xml.in" ]]; then
            CX_TEMPLATE="${CX_PLATFORM_DIR}/spinor/contents.xml.in"
        fi

        CX_PARTITION_XML="${CX_PTOOL_WORK}/partition_spinor.xml"
        if [[ -n "$CX_TEMPLATE" && -f "$CX_PARTITION_XML" ]]; then
            CX_OUT="${CX_TARGET_DIR}/spinor/contents.xml"
            python3 "${PTOOL_DIR}/gen_contents.py" \
                -t "$CX_TEMPLATE" \
                -p "$CX_PARTITION_XML" \
                -o "$CX_OUT"
            echo "[INFO] Written: ${CX_OUT}"

            # Patch rootfs.img path to ../../rootfs.img
            python3 -c "
import re
with open('${CX_OUT}') as f: c = f.read()
c = re.sub(
    r'(<file_name>rootfs\.img</file_name>\s*<file_path[^>]*>)[^<]*(</file_path>)',
    r'\g<1>../../\g<2>', c)
with open('${CX_OUT}', 'w') as f: f.write(c)
"
            echo "[INFO] Patched rootfs.img path in ${CX_OUT}"

            # Patch OS storage paths: NVME/ -> ../nvme/, UFS/ -> ../ufs/ etc.
            for s in "${CX_STORAGES[@]}"; do
                case "$s" in
                    nvme)  sed -i "s|>NVME/<|>../nvme/<|g"  "$CX_OUT" ;;
                    ufs)   sed -i "s|>UFS/<|>../ufs/<|g"    "$CX_OUT" ;;
                    emmc)  sed -i "s|>EMMC/<|>../emmc/<|g"  "$CX_OUT" ;;
                esac
            done
            echo "[INFO] Patched OS storage paths in ${CX_OUT}"
        else
            echo "[WARN] Skipping spinor contents.xml for ${CX_BOARD}: template or partition XML not found"
        fi

    else
        # No-spinor target: one contents.xml per storage dir
        for s in "${CX_STORAGES[@]}"; do
            CX_TEMPLATE=""
            [[ -f "${CX_PLATFORM_DIR}/${s}/contents.xml.in" ]] && \
                CX_TEMPLATE="${CX_PLATFORM_DIR}/${s}/contents.xml.in"
            CX_PARTITION_XML="${CX_PTOOL_WORK}/partition_${s}.xml"
            if [[ -n "$CX_TEMPLATE" && -f "$CX_PARTITION_XML" ]]; then
                CX_OUT="${CX_TARGET_DIR}/${s}/contents.xml"
                python3 "${PTOOL_DIR}/gen_contents.py" \
                    -t "$CX_TEMPLATE" \
                    -p "$CX_PARTITION_XML" \
                    -o "$CX_OUT"
                echo "[INFO] Written: ${CX_OUT}"
                # Patch rootfs.img path to ../../rootfs.img
                python3 -c "
import re
with open('${CX_OUT}') as f: c = f.read()
c = re.sub(
    r'(<file_name>rootfs\.img</file_name>\s*<file_path[^>]*>)[^<]*(</file_path>)',
    r'\g<1>../../\g<2>', c)
with open('${CX_OUT}', 'w') as f: f.write(c)
"
                echo "[INFO] Patched rootfs.img path in ${CX_OUT}"
            else
                echo "[INFO] No contents.xml.in for ${CX_BOARD}/${s} — skipping"
            fi
        done
    fi
done

echo ""
echo "[INFO] gen-flash-dirs.sh complete. Output: ${OUTPUT_DIR}"
