workflow_content = """name: Qualcomm Preflight Checks

on:
  pull_request_target:
    branches:
      - main
      - latest

  push:
    branches:
      - main
      - latest

  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  qcom-preflight-checks:
    uses: qualcomm/qcom-reusable-workflows/.github/workflows/qcom-preflight-checks-reusable-workflow.yml@v1.1.4
    with:
      repolinter: true
      semgrep: true
      copyright-license-detector: true
      pr-check-emails: true
      dependency-review: true
    secrets:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
"""

# Create the workflow file in the appropriate directory
import os

workflow_dir = ".github/workflows"
os.makedirs(workflow_dir, exist_ok=True)

workflow_path = os.path.join(workflow_dir, "preflight.yml")
with open(workflow_path, "w") as f:
    f.write(workflow_content)

print(f"Workflow file created at: {workflow_path}")
